---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-config.yaml
  - cert-manager.yaml
  - nginx-ingress.yaml
  - lgtm
  - tailscale.yaml
  #  - tailscale-secret.yaml
