---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gpu
  - metallb
  - observability
  - storage
  - cilium-values.yaml
  - cert-manager.yaml
  - nginx-ingress.yaml
  - tailscale.yaml
  - tailscale-secret.yaml
